<?php
/**
 * functions and definitions
 *
 * @package Go Galapagos
 */

if ( ! defined( 'ABSPATH' ) ) {
  exit; // Exit if accessed directly.
}

setlocale(LC_MONETARY, 'en_US' );


// DEREGISTER NATIVE JQUERY
if (!is_admin()) add_action("wp_enqueue_scripts", "my_jquery_enqueue", 10);
function my_jquery_enqueue() {
   wp_deregister_script('jquery');
   wp_register_script('jquery', get_stylesheet_directory_uri() . '/bootstrap/jquery.js', false, null);
   wp_enqueue_script('jquery');
}

function bower_enqueue_assets() {
  /*
   * BOWER - Generated by `gulp wiredep` - do not modify, use `bower install`
   *         and `bower uninstall` and run `gulp` to update this.
   * *************************************************************************/



  wp_enqueue_style('styles-bundle', get_stylesheet_directory_uri() . '/dist/sitio.css');
  wp_enqueue_script('parcel-bundle', get_stylesheet_directory_uri() . '/dist/sitio.js', '', '', true);


  // if(is_front_page() ){
  //     wp_enqueue_style('principal-css', get_stylesheet_directory_uri() . '/styles/principal.css');
  // }
  // elseif(is_page()){
  //     wp_enqueue_style('paginas-css', get_stylesheet_directory_uri() . '/styles/paginas.css');
  // }





//   if(is_front_page() ){
//       wp_enqueue_script('principal-js', get_stylesheet_directory_uri() . '/scripts/principal.js', '', '', true);
//   }
//   elseif(is_page()){
//       wp_enqueue_script('paginas-js', get_stylesheet_directory_uri() . '/scripts/paginas.js', '', '', true);

// }

  }

add_action('wp_enqueue_scripts', 'bower_enqueue_assets');

// THUMBNAIL-SUPPORT
add_theme_support( 'post-thumbnails' ); 
// NAVWALKER
require_once get_template_directory() . '/wp-bootstrap-navwalker.php';
register_nav_menus( array(
  'primary' => __( 'Primary Menu', 'menu_principal' ),
) );



// Register Theme Features
function titulo()  {

  // Add theme support for document Title tag
  add_theme_support( 'title-tag' );
}
add_action( 'after_setup_theme', 'titulo' );
